events {
    worker_connections 1024; # количество io операций на процесс
}

http {
    # формат access лога должен совпадать с regex в parser.py
    log_format main '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';
    
    server {
        listen 80; #дефеолтный порт
        server_name localhost;
        
        access_log /var/log/nginx/app_access.log main; #создаем кастомные пути, тк обычный создает symlink на stdout
        error_log /var/log/nginx/app_error.log; #а stdout перехватывает docker log, в проде так обычно и оставляют, у нас офлайн отладка
        
        # endpoint для healthcheck
        location /health {
            return 200 "OK\n";
            add_header Content-Type text/plain;
        }
        
        # api endpoints (для генерации разных статусов)
        location /api/ {
            return 200 '{"status": "ok"}\n';
            add_header Content-Type application/json;
        }
        
        # not found (404)
        location /notfound {
            return 404 '{"error": "not found"}\n';
        }
        
        # server error (500)
        location /error {
            return 500 '{"error": "server error"}\n';
        }
        
        # forbidden (403)
        location /forbidden {
            return 403 '{"error": "forbidden"}\n';
        }
        
        location / { # основная точка приложения
            return 200 "Welcome to Log Generator\n";
        }
    }
}