name: CI Pipline

on:
  push:
    branches: 
    - main #сработает при пуше в main и develop ветки
    - develop
    - 'develop/**'  # все ветки, начинающиеся с develop/
  pull_request: 
    branches: 
    - main #при пулл реквесте в мейн  
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.14"
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/log-analyzer #ссылка на гихаб регистри проекта

jobs:
  lint: # job
    name: Lint code
    runs-on: self-hosted #указываем что запускаем локально  

    steps:
      - name: Checkout code 
        uses: actions/checkout@v7 #готовый переиспользуемый модуль, клонирует репозиторий в job 
      
      - name: Установка python + poetry и кеширование зависимостей .venv
        uses: ./.github/actions/setup-python-poetry
        with: 
          python-version: 3.14
      
      - name: Run Ruff linter
        run: poetry run ruff check src/ tests/
      
      - name: Check code formatting with Black
        run: poetry run black --check src/ tests/

  test: 
    name: Test Python ${{ matrix.python_version }} 
    runs-on: self-hosted
    needs: lint # запускаем после успешного lint

    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.14']
      fail-fast: false #продолжит если одна упала

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name:  Установка python + poetry и кеширование зависимостей .venv
        uses: ./.github/actions/setup-python-poetry
        with: 
          python-version: ${{ matrix.python_version }}

      
      - name: Запуск тестов
        run: | # запускаем тесты с отчетом по покрытию кода
          poetry run pytest --cov=src --cov-report=xml --cov-report=term-missing 
        
      - name: Загрузка отчета покрытия тестами
        if: matrix.python-version == '3.14'
        uses: codecov/codecov-action@v7
        with: 
          files: ./coverage.xml #файл отчета 
          flags: unittests
          name: codecov-umbrella #пользовательское название
          fail_ci_if_error: false

  build: 
    name: Build Docker Image
    runs-on: self-hosted
    needs: test #выполнится только после успешных тестов

    outputs: #указываем что получаем на выходе, проброс данных, сможем использовать в других джобах
      image-digest: ${{ steps.build.outputs.digest }} #хеш(sha) образа
      image-tag: ${{ steps.meta.outputs.tags }} #теги образа(все)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Сетап docker buildx #создаем сборщик образов
        uses: docker/setup-buildx-action@v4
      
      - name: Сбор метаданных с репозитория 
        id: meta 
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch  
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v7
        with:
          context: . #указываем откуда брать dockerfile 
          push: false  # Не пушим в CI, только билдим
          tags: ${{ steps.meta.outputs.tags }} #используем тег для образа из метаданных
          labels: ${{ steps.meta.outputs.labels }} 
          cache-from: type=gha #используем кеш github actions
          cache-to: type=gha,mode=max #кешируем в github actions и используем все слои для кеша
          outputs: type=docker #локальное сохранение сборки
       
      - name: Test Docker image
        # Проверяем что образ работает
        run: |
          IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)
          echo "Testing image: $IMAGE_TAG"
          docker run --rm "$IMAGE_TAG" --help || echo "Warning: --help failed, but continuing"