name: CI Pipline

on:
  workflow_dispatch:
  push:
    branches: 
    - main #сработает при пуше в main и develop ветки
    - develop
    - 'develop/**'  # все ветки, начинающиеся с develop/
  pull_request: 
    branches: 
    - main #при пулл реквесте в мейн  

env:
  PYTHON_VERSION: "3.14"
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/log-analyzer #ссылка на гихаб регистри проекта

jobs:
  lint: # job
    name: Lint code
    runs-on: self-hosted #указываем что запускаем локально  

    steps:
      - name: Checkout code 
        uses: actions/checkout@v7 #готовый переиспользуемый модуль, клонирует репозиторий в job 
      
      - name: Установка python + poetry и кеширование зависимостей .venv
        uses: ./.github/actions/setup-python-poetry
        with: 
          python-version: 3.14
      
      - name: Run Ruff linter
        run: poetry run ruff check src/ tests/
      
      - name: Check code formatting with Black
        run: poetry run black --check src/ tests/

  test: 
    name: Test Python ${{ matrix.python_version }} 
    runs-on: self-hosted
    needs: lint # запускаем после успешного lint

    strategy:
      matrix:
        python-version: ['3.12', '3.13', '3.14']
      fail-fast: false #продолжит если одна упала

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name:  Установка python + poetry и кеширование зависимостей .venv
        uses: ./.github/actions/setup-python-poetry
        with: 
          python-version: ${{ matrix.python_version }}

      
      - name: Запуск тестов
        run: | # запускаем тесты с отчетом по покрытию кода
          poetry run pytest --cov=src --cov-report=xml --cov-report=term-missing 
        
      - name: Загрузка отчета покрытия тестами
        if: matrix.python-version == '3.14'
        uses: codecov/codecov-action@v7
        with: 
          files: ./coverage.xml #файл отчета 
          flags: unittests
          name: codecov-umbrella #пользовательское название
          fail_ci_if_error: false
